### ISSUE TITLE
Question on html templates?

### ISSUE THREAD

**Issue by aivijay** [jgdavey/kevin#2]
I am wondering how you generated the html content? I see a file named d in the source which seems to generate the html content using middleman. I don't know what I am missing. How do I get the relevant html content for this. Or do you have the content somewhere?

**Comment by jgdavey** [comment]
All the design files for this project are on [the design branch](https://github.com/jgdavey/kevin/tree/design). However, since doing this project, I've come up with what I think is a better way to work with design files. Rather than a separate branch, I use [boot-middleman](https://github.com/jgdavey/boot-middleman), a boot plugin that embeds a middleman process (using JRuby).

I wrote about this experience here: https://hashrocket.com/blog/posts/the-front-end-development-environment-of-my-dreams
