### ISSUE TITLE
More about the associated blog post and scalability

### ISSUE THREAD

**Issue by matanox** [jgdavey/kevin#3]
I'm not sure what [this here](https://hashrocket.com/blog/posts/using-datomic-as-a-graph-database#low-level-traversal-for-better-performance) is actually telling:

> Having to know the depth at which to traverse the graph is cumbersome. Datomic has a distinct advantage of being able to treat your data as local, even if its permanent storage lives somewhere else. That means that we can bring our own functions to the problem and execute locally, rather than on a database server. We can leverage Datomic's datoms function to search the graph using our own graph-searching algorithm, rather than relying on the query engine.

Does it mean the entire graph is actually loaded in-memory on the peer machine? that approach won't really scale for large graphs would it?

**Comment by jgdavey** [comment]
@matanster No, the whole graph does not need to be loaded into memory. Quite the opposite. In my local testing, I never let my JVM size get beyond the size of the dataset. Of course, allowing Datomic to use more memory for its Object Cache can improve performance, but because of JVM bookkeeping overhead, that benefit degrades at really high Xmx settings.

Although it's a fairly opaque process, Datomic brings over large "chunks" of data from storage when it doesn't have the relevant objects in its local (peer) cache. And of course, parts of that cache are discarded at various times. In effect, this means that we can *treat* the data as local even though it lives elsewhere.

**Comment by matanox** [comment]
> In effect, this means that we can treat the data as local even though it lives elsewhere.

Well, not really, but under some circumstances you may not need to think that much about how overall datomic performance will degrade your actual performance.
